# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: vcloud-rest 1.6.4 ruby lib

Gem::Specification.new do |s|
  s.name = "vcloud-rest"
  s.version = "1.6.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Stefano Tortarolo", "Gareth Jones"]
  s.date = "2014-04-01"
  s.description = "Ruby bindings to create, list and manage vCloud servers"
  s.email = ["stefano.tortarolo@gmail.com", "gareth.jones@pearson.com"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "CHANGELOG.md",
    "LICENSE",
    "README.md",
    "lib/vcloud-rest/connection.rb",
    "lib/vcloud-rest/vcloud/catalog.rb",
    "lib/vcloud-rest/vcloud/edgegateway.rb",
    "lib/vcloud-rest/vcloud/network.rb",
    "lib/vcloud-rest/vcloud/org.rb",
    "lib/vcloud-rest/vcloud/ovf.rb",
    "lib/vcloud-rest/vcloud/vapp.rb",
    "lib/vcloud-rest/vcloud/vapp_networking.rb",
    "lib/vcloud-rest/vcloud/vdc.rb",
    "lib/vcloud-rest/vcloud/vm.rb",
    "lib/vcloud-rest/version.rb"
  ]
  s.homepage = "https://github.com/pearsoncloud/vcloud-rest"
  s.licenses = ["Apache 2.0"]
  s.rubygems_version = "2.2.2"
  s.summary = "Unofficial ruby bindings for VMWare vCloud's API"

end

